[mainConfig]
appName = "ChatService"
host = "0.0.0.0"
port = 9092

[emailConfig]
authcode = "your authcode"
email = "your email"

[redisConfig]
host = "127.0.0.1"
port = 6379
password = ""
db = 0

[mysqlConfig]
host = "127.0.0.1"
port = 3307
user = "root"
password = "password"
databaseName = "visionrag"
charset = "utf8mb4"

[rabbitmqConfig]
host = "127.0.0.1"
port = 5672
username = "guest"
password = "guest"
vhost = "/"