[mainConfig]
appName = "GatewayService"
host = "0.0.0.0"
port = 9090

[emailConfig]
authcode = "your authcode"
email = "your email"

[redisConfig]
host = "127.0.0.1"
port = 6379
password = ""
db = 0

[databaseConfig]
host = "127.0.0.1"
port = 5432
user = "postgres"
password = "password"
databaseName = "visionrag"
sslmode = "disable"
timezone = "America/Vancouver"

[rabbitmqConfig]
host = "127.0.0.1"
port = 5672
username = "guest"
password = "guest"
vhost = "/"

[jwtConfig]
expire_duration = 24
issuer = "VisionRAG"
subject = "Gateway"
key = "SecretKeyChangeMe"